mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('reg/', include('requestdataapp.urls')),
]

mysite/requestdataapp/urls.py
from django.urls import path

from .views import process_get_view, user_form, handle_file_upload

app_name = "requestdataapp"

urlpatterns = [
    path("get/", process_get_view, name="get-view"),
    path("bio/", user_form, name="user-form"),
    path("upload/", handle_file_upload, name="file_upload"),
]

mysite/shopapp/urls.py
from django.urls import path

from .views import ShopIndexView, GroupsListView, products_list, order_list, create_product, ProductDetailsView

app_name = "shopapp"

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", products_list, name="products_list"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/create/", create_product, name="product_create"),
    path("orders/", order_list, name="orders_list"),
]

mysite/requestdataapp/models.py
from django.db import models

# Create your models here.

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]
        # db_table = "tech_products"
        # verbose_name_plural = "products"

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self) -> str:
        # return f"Product(pk={self.pk}, name={self.name!r})"
        return self.name


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

    # def __str__(self) -> str:
    #     # return f"Product(pk={self.pk}, name={self.name!r})"
    #     return self.delivery_address

mysite/requestdataapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile


class UserBioForm(forms.Form):
    name = forms.CharField(max_length=20)
    age = forms.IntegerField(label="You age", min_value=1, max_value=99)
    bio = forms.CharField(label="Biography", widget=forms.Textarea)

def validate_file_name(file: InMemoryUploadedFile) -> None:
    if file.name and "virus" in file.name:
        raise ValidationError("file name should not contain `virus`")

class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[validate_file_name])

mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django import forms
from django.forms.models import ModelForm

from .models import Product

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name","price","description","discount"

# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"rows": 5, "cols": 30}),
#         validators=[validators.RegexValidator(
#             regex=r"great",
#             message="Field must contain word 'great"
#         )]
#     )

mysite/requestdataapp/views.py
from django.core.files.storage import FileSystemStorage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .forms import UserBioForm, UploadFileForm


def process_get_view(request: HttpRequest) -> HttpResponse:
    a = request.GET.get("a", "")
    b = request.GET.get("b", "")
    result = a + b
    context = {
        "a": a,
        "b": b,
        "result": result,
    }
    return render(request,"requestdataapp/request-query-params.html", context=context)

def user_form(request: HttpRequest) -> HttpResponse:
    context = {
        "form": UserBioForm(),
    }
    return render(request, "requestdataapp/user-bio-form.html", context=context)

def handle_file_upload(request: HttpRequest) -> HttpResponse:

    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            #myfile = request.FILES["myfile"]
            myfile = form.cleaned_data["file"]
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
    else:
        form = UploadFileForm()

    context = {
        "form": form,
    }

    return render(request, "requestdataapp/file-upload.html", context=context)

mysite/shopapp/views.py
from timeit import default_timer

from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View

from .models import Product, Order
from .forms import ProductForm, GroupForm

class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
        }
        return render(request, 'shopapp/shop-index.html', context=context)

class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)

class ProductDetailsView(View):
    def get(self, request: HttpRequest, pk: int) -> HttpResponse:
        product = get_object_or_404(Product, pk=pk)
        context = {
            "products": product,
        }
        return render(request, 'shopapp/products-details.html', context=context)

def products_list(request: HttpRequest):
    context = {
        "products": Product.objects.all(),
    }
    return  render(request, 'shopapp/products-list.html', context=context)

def create_product(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            # Product.objects.create(**form.cleaned_data)
            form.save()
            url = reverse('shopapp:products_list')
            return redirect(url)
    else:
        form = ProductForm()
    context = {
        "form": form,
    }
    return render(request, 'shopapp/create-product.html', context=context)

def order_list(request: HttpRequest):
    context = {
        "orders": Order.objects.select_related("user").prefetch_related('products').all()
    }
    return render(request, 'shopapp/order-list.html', context=context)

mysite/requestdataapp/templates/requestdataapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        	
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
	
{% endblock %}

<br>

</body>
</html>

mysite/requestdataapp/templates/requestdataapp/file-upload.html
{% extends 'requestdataapp/base.html' %}

{% block title %}
	File upload
{% endblock %}

{% block body %}
	<h1>Upload file</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        
        {{ form.as_p }}
  
        <button type="submit">
            Upload
        </button>
    </form>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/request-query-params.html
{% extends 'requestdataapp/base.html' %}

{% block title %}
    Demo request params
{% endblock %}

{% block body %}
    <h1>Good afternoom, {%  firstof request.GET.name 'User' %}</h1>

    <div>
    <pre>
        a = '{{ a }}'
        b = '{{ b }}'
        result = '{{ result }}'
    </pre>
    </div>
{% endblock %}

mysite/requestdataapp/templates/requestdataapp/user-bio-form.html
{% extends 'requestdataapp/base.html' %}

{% block title %}
	User BIO
{% endblock %}

{% block body %}
	<h1>User form</h1>
    <div>
        <form method="post" action="">
            {% csrf_token %}

                {{ form.as_p }}

            <button type="submit">
                Submit
            </button>
        </form>
    </div>
    
    {% if request.POST %}
        <div>
            <h2>Previous form data:</h2>
        <table>
            <tr>
                <td>Full name:</td>
                <td>{{ request.POST.name }}</td>
            </tr>

            <tr>
                <td>Age:</td>
                <td>{{ request.POST.age }}</td>
            </tr>

            <tr>
                <td>Bio:</td>
                <td>
                    <p>
                        {{ request.POST.bio|linebreaks }}
                    </p>
                </td>
            </tr>
        </table>
        </div>
    {% endif %} 
{% endblock %}

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock title %}
    </title>
</head>
<body>

    {% block body %}
        Base body
    {% endblock body %}

<div>
    {% now 'H : i' %}
</div>

<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Create Product
{% endblock %}

{% block body %}
	<h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to product list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Groups List
{% endblock %}

{% block body %}
	<h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
   <div>
   {% if not groups %}
       <h3>No groups yet</h3>
   {% else %}
       <ul>
        {% for group in groups %}
            <li>
            <div>{{ group.name }}</div>
            <ul>
                {% for permission in group.permissions.all %}
                	<li>
                        {{ permission.name }}
                        (<code>{{ permission.codename }}</code>)
                    </li>
                {% endfor %}

            </ul>
            </li>
        {% endfor %}
       </ul>
   {% endif %}

   
   </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order-list.html
{% extends 'shopapp/base.html' %}


{% block title %}
    Order list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if orders %}
    	<div>
        {% for order in orders %}
        	<div>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
            <div>
                Product in order
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}

                </ul>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ products.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ products.name }}</strong></h1>
    <div>
    <div>
        Description: <em>{{ products.description }}</em>
    </div>
    <div>
        Price: {{ products.price }}
    </div>
    <div>
        Discount: {{ products.discount }}
    </div>
    <div>
        Archived: {{ products.archived }}
    </div>
    </div>
    
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
	Product list
{% endblock %}

{% block body %}
	<h1>Products:</h1>
    {% if products %}
        <div>
        {% for product in products %}
            <div>
                <p>Name: <a href="{% url 'shopapp:product_details' pk=product.pk%}">{{ product.name }}</a></p>
                <p>Price: {% firstof product.price 'No price' %}</p>
                <p>Discount: {% firstof product.discount 'No discount' %}</p>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>No produts yet</h3>
    {% endif %}
    
    <div>
        <a href="{% url 'shopapp:product_create' %}">Create a new product</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock title %}


{% block body %}

    <h1> Hello Shop Index! </h1>
    
    <div>
        <ul>
            {% for name, price in products %}
            	<li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
                {% if name|length == 7 %}
                	<span>Lucky product!</span>
                {% endif %} 
            {% empty %}
                No products here
            {% endfor %}
            
        </ul>
    </div>

    <div>
        Time running: {{ time_running }}
    </div>

    <div>
        {% lorem 3 p random %}
    </div>

{% endblock body %}